## WHAT IS PEP 8

PEP 8 IS DEFIND AS A DOCUMETS THAT HELPS US TO PROVIDES THE GUIDELINES ON HOW TO WRITE THE PYTHON CODE .
 IT WAS WRITTEN BY GUIDE VAN ROSSUM, BARRY WARSAW AND NICK COGHLAN IN 2001 .__abs__()

IT STANDS FOR PYTHON ENHANCEMENT PROPOSAL, AND ITS MAJOR TASK IS TO IMPROVE 
THE READABILITY AND CONSISTENCY OF PYTHON CODE . 

## PYTHON LITERALS

LITERALS CAN BE DEFINED AS A DATA WHICH IS GIVEN IN A VARIABLE or
CONSTANT . PYTHON SUPPORTS THE FOLLOWING LITERALS 

STRING LITERALS (FORMED BY ENCLOSING TEXT IN THE SINGLE OR DOUBLE QUOTES)

NUMBERIC LITERALS(PYTHON SUPPORTS THREE TYPES OF NUMERIC LITERALS INTEGER, FLOAT AND COMPLEX .)

BOOLEAN LITERALS (USED TO DENOTE BOOLEAN VALUES. IT CONTAINS EITHER TRUE OR FALSE)

