#  ADVANTAGES OF PYTHON 

INTERPRETED 

FREE AND OPEN SOURCE 

EXTENSIBLE

OBJECT - ORIENTED

BUILT-IN DATA STRUCTURE

READABILITY

HIGH- LEVEL LANGUAGE

CROSS-PLATFORM

#------------------------------------

# WHAT IS PYTHON 

PYTHON WAS CREATED BY GUIDO VAN ROSSUM, AND RELEASED IN 1991.and

IT IS A GENERAL-PURPOSE COMPUTER PROGRAMMING LANGUAGE .
IT IS A HOGH-LEVEL, OBJECT-ORIENTED LANGUAGE WHICH CAN RUN EQUALLY ON DIFFERENT PLATFORMS SUCH AS WINDOWS,
 LINUX,UNIX,AND MACINTOSH. IT US WIDELY USED IN DATA SCIENCE, 
 MACHINE LEARNING AND ARTIFICAL INTELLIGENCE DOMAIN .