PYTHON INTERMEDIADTE TOPICS

DATA STRUCTURES  : TRESS , GRAPHS , QUEUES , STACKS, HEAPS , LINKED LISTS

OOPS  : CLASS, OBJECT ,METHOD , INHERITANCE , POLYMORPHISM , DATA ABSTRACTION , ENCAPSULATION 

DATABASE : SQL , NOSQL 

ALGORITHMS : SORTING , SEARCHING ALGORITHMS