WHAT YOU WILL LEARN IN PYTHON

PYTHON PROGRAMMING BASIC TO ADVANCED

WORKING ON DJANGO FRAMEWORK AND VARIOUS IDES

PYTHON SCRIPTING FOR AUTOMATION

BUILDING PYTHON APPLICATION

DEPLOYING WEB APPLICATION WITH PYTHON AND DJANGO

OOP IN PYTHON AND SO MUCH MORE !