APPLICATION OF PYTHON 

WEB AND INTERNET DEVELOPMENT

GAMES

SCIENTIFIC AND COMPUTATIONAL APPLICATIONS

LANGUAGE DEVELOPMENT

IMAGES PROCESSING AND GRAPHIC DESIGN APPLICATION

ENTERPRISE AND BUSINESS APPLICATION DEVELOPMENT

OPERATING SYSTEMS

GUI BASED DESKTOP APPLICATION